### ISSUE TITLE
Delegate Method error

### ISSUE THREAD

**Issue by 90301** [90301/DynamicQuery#9]
I'm trying to set this static delegate method that will be called every time a "SELECT" Statement is fired off. It seems to be giving me an error, so I suppose I have the syntax wrong or something.

![image](https://user-images.githubusercontent.com/6025683/26854445-318cc230-4ae4-11e7-8f37-af44cd79e96b.png)

Inspired By:
https://stackoverflow.com/questions/7367152/dynamically-assign-method-method-as-variable

**Comment by forember** [comment]
You need to set the variable to a delegate implementation, not the delegate type.

Example:

```cs
public static DataTable MyImplementation(String query) {
    // Best implementation ever...
    return null;
}
// ...
QueryHolder.howDoISelect = MyImplementation;
```

**Comment by forember** [comment]
Closed: simply a mistype.
